# Form implementation generated from reading ui file 'AcaCrawl.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 298)
        self.RBSelection = QtWidgets.QRadioButton(parent=Form)
        self.RBSelection.setGeometry(QtCore.QRect(370, 150, 99, 20))
        self.RBSelection.setObjectName("RBSelection")

        self.SearchButton = QtWidgets.QPushButton(parent=Form)
        self.SearchButton.setGeometry(QtCore.QRect(370, 240, 80, 22))
        self.SearchButton.setObjectName("SearchButton")
        
        self.ExportButton = QtWidgets.QPushButton(parent=Form)
        self.ExportButton.setGeometry(QtCore.QRect(500, 240, 80, 22))
        self.ExportButton.setObjectName("ExportButton")
        
        self.SearchLine = QtWidgets.QLineEdit(parent=Form)
        self.SearchLine.setGeometry(QtCore.QRect(50, 60, 551, 22))
        self.SearchLine.setObjectName("SearchLine")
        
        self.SearchLabel = QtWidgets.QLabel(parent=Form)
        self.SearchLabel.setGeometry(QtCore.QRect(60, 30, 131, 16))
        self.SearchLabel.setObjectName("SearchLabel")
        
        self.SelectionLabel = QtWidgets.QLabel(parent=Form)
        self.SelectionLabel.setGeometry(QtCore.QRect(370, 110, 141, 16))
        self.SelectionLabel.setObjectName("SelectionLabel")
        
        self.PagesNumber = QtWidgets.QSpinBox(parent=Form)
        self.PagesNumber.setGeometry(QtCore.QRect(370, 190, 43, 23))
        self.PagesNumber.setObjectName("PagesNumber")
        
        self.ComsLabel = QtWidgets.QTextBrowser(parent=Form)
        self.ComsLabel.setGeometry(QtCore.QRect(50, 100, 301, 81))
        self.ComsLabel.setObjectName("ComsLabel")
        
        self.PagesLabel = QtWidgets.QLabel(parent=Form)
        self.PagesLabel.setGeometry(QtCore.QRect(440, 190, 57, 21))
        self.PagesLabel.setObjectName("PagesLabel")
        
        self.ComsLabel_2 = QtWidgets.QTextBrowser(parent=Form)
        self.ComsLabel_2.setGeometry(QtCore.QRect(50, 190, 301, 81))
        self.ComsLabel_2.setObjectName("ComsLabel_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RBSelection.setText(_translate("Form", "Todo"))
        self.SearchButton.setText(_translate("Form", "Buscar"))
        self.ExportButton.setText(_translate("Form", "Exportar"))
        self.SearchLabel.setText(_translate("Form", "Ingrese su búsqueda"))
        self.SelectionLabel.setText(_translate("Form", "Páginas a descargar"))
        self.PagesLabel.setText(_translate("Form", "Paginas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
