'''
AcaCrawl v.2.0
Form implementation generated from reading ui file 'AcaCrawl.ui'
Created by: PyQt6 UI code generator 6.4.2
WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
'''

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

class TableModel(QtCore.QAbstractTableModel):
    def __init__(self, data):
        super(TableModel, self).__init__()
        self._data = data
        
    def data(self, index, role):
        if role == Qt.ItemDataRole.DisplayRole:
            # See below for the nested-list data structure.
            # .row() indexes into the outer list,
            # .column() indexes into the sub-list
            return self._data[index.row()][index.column()]
        # Get the Article object from the data list
            #article = self._data[index.row()]

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)

        self.SelectionAll = QtWidgets.QRadioButton(parent=Form)
        self.SelectionAll.setGeometry(QtCore.QRect(370, 150, 99, 20))
        self.SelectionAll.setObjectName("SelectionAll")
        self.SelectionAll.toggled.connect(self.showDetails)

        self.ResultsTable = QtWidgets.QTableView(parent=Form)
        self.ResultsTable.setGeometry(QtCore.QRect(50, 230, 541, 191))
        self.ResultsTable.setObjectName("ResultsTable")

        self.table = QtWidgets.QTableView()

        # IMPORTANT: THIS IS A HALF WORKING EXAMPLE. ON TESTING, NESTED ARRAYS WILL NOT PRINT NORMALLY ON TABLE MODELS
        data = [
          ['Id', 'Title', 'Authors', 'Abstracts', 'DOI', 'Country'],
          [1234, 'TestTitle', ['TestAuthors1','TestAuthors2'],['TestAbstracts1','TestAbstracts2'], 'TestDoi', 'COU']
        ]

        self.model = TableModel(data)
        self.ResultsTable.setModel(self.model)
        '''
        '''

        self.SearchButton = QtWidgets.QPushButton(parent=Form)
        self.SearchButton.setGeometry(QtCore.QRect(410, 440, 80, 22))
        self.SearchButton.setObjectName("SearchButton")
        self.SearchButton.clicked.connect(self.run_search)
         
        self.CloseButton = QtWidgets.QPushButton(parent=Form)
        self.CloseButton.setGeometry(QtCore.QRect(510, 440, 80, 22))
        self.CloseButton.setObjectName("CloseButton")
        self.CloseButton.clicked.connect(self.run_close)
        
        self.SearchLine = QtWidgets.QLineEdit(parent=Form)
        self.SearchLine.setGeometry(QtCore.QRect(50, 60, 551, 22))
        self.SearchLine.setObjectName("SearchLine")
        self.SearchLine.textChanged.connect(self.onChanged)
        
        self.SearchLabel = QtWidgets.QLabel(parent=Form)
        self.SearchLabel.setGeometry(QtCore.QRect(60, 30, 131, 16))
        self.SearchLabel.setObjectName("SearchLabel")
        
        self.SelectionLabel = QtWidgets.QLabel(parent=Form)
        self.SelectionLabel.setGeometry(QtCore.QRect(370, 110, 141, 16))
        self.SelectionLabel.setObjectName("SelectionLabel")
        
        self.PagesNumber = QtWidgets.QSpinBox(parent=Form)
        self.PagesNumber.setGeometry(QtCore.QRect(370, 190, 43, 23))
        self.PagesNumber.setObjectName("PagesNumber")
        self.PagesNumber.valueChanged.connect(self.update_pages)
        
        self.ComsLabel = QtWidgets.QTextBrowser(parent=Form)
        self.ComsLabel.setGeometry(QtCore.QRect(50, 100, 301, 121))
        self.ComsLabel.setObjectName("ComsLabel")
        
        self.PagesLabel = QtWidgets.QLabel(parent=Form)
        self.PagesLabel.setGeometry(QtCore.QRect(440, 190, 57, 21))
        self.PagesLabel.setObjectName("PagesLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def update_pages(self, value):
        self.ComsLabel.setText(str(value))


    def run_search(self):
        print("Search Button Clicked")

    def run_close(self):
        print("Close Button Clicked")

    def showDetails(self):
        print("Selected: ", self.sender().isChecked(), "  Name: ", self.sender().text())

    def onChanged(self, text):
        self.ComsLabel.setText(text)
        #self.ComsLabel.adjustSize()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SelectionAll.setText(_translate("Form", "Descargar todo"))
        self.SearchButton.setText(_translate("Form", "Buscar"))
        self.CloseButton.setText(_translate("Form", "Cerrar"))
        self.SearchLabel.setText(_translate("Form", "Ingrese su búsqueda"))
        self.SelectionLabel.setText(_translate("Form", "Páginas a descargar"))
        self.PagesLabel.setText(_translate("Form", "Paginas"))